language: php

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.example .env
  - composer self-update
  - composer install --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

script:
  - vendor/bin/phpunit

cache:
  directories:
    - $HOME/.composer/cache